import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CheerpxProvider } from "../providers/cheerpx";
import { getLatestCheerpxScriptUrl } from "@/lib/get-latest-cheerpx-script-url";
import "@xterm/xterm/css/xterm.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const scriptUrl = await getLatestCheerpxScriptUrl();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="root">
          <CheerpxProvider src={scriptUrl}>{children}</CheerpxProvider>
        </div>
      </body>
    </html>
  );
}
